AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 3GPP Milenage Authentication API Infrastructure

Resources:
  MilenageAuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src/task4/
      Handler: auth_api.handler
      Runtime: nodejs14.x
      Timeout: 30
      Environment:
        Variables:
          SECRET_KEY_ARN: !Ref OPSecretKey
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref OPSecretKey
      Events:
        AuthVector:
          Type: Api
          Properties:
            Path: /generate-av
            Method: post

  OPSecretKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: milenage/op-secret-key
      Description: Secret keys for Milenage authentication algorithm
      SecretString: '{"op":"00000000000000000000000000000000","secretKey":"00000000000000000000000000000000"}'

  AuthApiLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${MilenageAuthFunction}"
      RetentionInDays: 30

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint for Milenage authentication
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/generate-av"
  MilenageAuthFunction:
    Description: Milenage Authentication Lambda Function ARN
    Value: !GetAtt MilenageAuthFunction.Arn 